# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: nestjs-nest-rest-api
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password


  mongo-express:
    image: mongo-express
    container_name: nestjs-nest-rest-api-mongoexpress
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password


  #docker exec -it jobs-php-fpm /bin/bash

  #find /application/ -type f -exec chmod 644 {} \;
  #find /application -type d -exec chmod 755 {} \;
  #chown -R 1000:1000 /application/
  #chmod -R 777 /application/storage
  #chmod -R 777 /application/bootstrap/cache/
  #chmod -R 777 /application/public/js/builds
  #kompose convert -f docker-compose.yml
  #npm run list -- --init

